# CSE-CIC-IDS 2017 Random Forests

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm

import glob

In [2]:
NOTEBOOK_PATH = "D:/Delta Stuff/Scifair20/"

In [3]:
f_names = glob.glob(NOTEBOOK_PATH + "IDS2017/MachineLearningCVE/*.csv")
df = pd.concat(tqdm(pd.read_csv(f) for f in f_names))

0it [00:00, ?it/s]C:\Users\Xetrov\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\reshape\concat.py:255: DtypeWarning: Columns (14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  sort=sort,
3it [00:02,  1.01it/s]C:\Users\Xetrov\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\reshape\concat.py:255: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  sort=sort,
8it [00:12,  1.54s/it]

In [4]:
df.reset_index(drop=True, inplace=True)

In [5]:
df.columns = list(map(lambda x: x.strip(), df.columns))

In [6]:
# Remove variables with no variance
remove_vars = []
for i in tqdm(range(len(df.columns))):
    col = df.columns[i]
    unique = df[col].unique()
    if len(unique) <= 1:
        remove_vars.append(col)

100%|██████████████████████████████████████████████████████████████████████████████████| 79/79 [00:04<00:00, 19.51it/s]

In [7]:
remove_vars

['Bwd PSH Flags',
 'Bwd URG Flags',
 'Fwd Avg Bytes/Bulk',
 'Fwd Avg Packets/Bulk',
 'Fwd Avg Bulk Rate',
 'Bwd Avg Bytes/Bulk',
 'Bwd Avg Packets/Bulk',
 'Bwd Avg Bulk Rate']

In [8]:
df.drop(remove_vars, axis=1, inplace=True)

In [9]:
df.shape

(2830743, 71)

In [10]:
df.drop(["Flow Bytes/s", "Flow Packets/s"], axis='columns', inplace=True)

In [11]:
df.shape

(2830743, 69)

# Standardize data

In [12]:
from sklearn.preprocessing import PowerTransformer

In [13]:
scaler = PowerTransformer(method='yeo-johnson', standardize=True)

In [14]:
x_df = df.drop("Label", axis=1)
y_df = df.loc[:, "Label"]

In [15]:
x_df_ptscaled = scaler.fit_transform(x_df, y_df)

In [16]:
scaled_summary = pd.DataFrame(x_df_ptscaled, columns=x_df.columns).describe()
scaled_summary

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,2.830743e+06,2.830743e+06,2.830743e+06,2.830743e+06,2.830743e+06,2.830743e+06,2.830743e+06,2.830743e+06,2.830743e+06,2.830743e+06,...,2.830743e+06,2.830743e+06,2.830743e+06,2.830743e+06,2.830743e+06,2.830743e+06,2.830743e+06,2.830743e+06,2.830743e+06,2.830743e+06
mean,5.614575e-17,-5.294087e-16,-1.481637e-15,-7.895848e-16,-6.103742e-16,4.526701e-16,-2.069120e-16,-5.198502e-16,-1.929056e-15,1.910080e-16,...,-6.024222e-18,-1.909197e-15,-2.522141e-16,8.514234e-18,2.377560e-17,1.824135e-16,8.731106e-17,-3.527785e-16,-2.910904e-16,1.681963e-16
std,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,...,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
min,-8.085491e+00,-2.286645e+01,-1.304010e+00,-1.655424e+00,-1.617208e+00,-1.349540e+00,-1.591983e+00,-9.953509e-01,-1.640853e+00,-7.155903e-01,...,-1.200386e+00,-2.752211e+01,-4.925726e-01,-2.797894e-01,-4.923377e-01,-4.926216e-01,-5.006239e-01,-2.968475e-01,-5.006238e-01,-5.006238e-01
25%,-8.738939e-01,-8.876095e-01,-2.338725e-01,-4.381973e-01,-5.559671e-01,-1.349540e+00,-6.855578e-01,-9.953509e-01,-6.405733e-01,-7.155903e-01,...,-1.200386e+00,-9.087109e-01,-4.925726e-01,-2.797894e-01,-4.923377e-01,-4.926216e-01,-5.006239e-01,-2.968475e-01,-5.006238e-01,-5.006238e-01
50%,-5.280598e-01,1.134869e-01,-2.338725e-01,1.225253e-01,1.168017e-01,1.793477e-01,1.106896e-01,-1.864637e-01,3.389061e-01,-7.155903e-01,...,1.163599e-01,-3.832149e-01,-4.925726e-01,-2.797894e-01,-4.923377e-01,-4.926216e-01,-5.006239e-01,-2.968475e-01,-5.006238e-01,-5.006238e-01
75%,5.271538e-01,9.319696e-01,8.888288e-01,7.029430e-01,5.919397e-01,5.791860e-01,4.752672e-01,1.140584e+00,5.905137e-01,1.240967e+00,...,6.579127e-01,8.493489e-01,-4.925726e-01,-2.797894e-01,-4.923377e-01,-4.926216e-01,-5.006239e-01,-2.968475e-01,-5.006238e-01,-5.006238e-01
max,1.713337e+00,1.538709e+00,2.168643e+00,3.041949e+00,5.883933e+00,4.035647e+00,3.233995e+00,2.329224e+00,4.685579e+00,1.704225e+00,...,2.511256e+00,3.492139e+01,2.093608e+00,3.576140e+00,2.098229e+00,2.092428e+00,2.006166e+00,3.369526e+00,2.006018e+00,2.006746e+00

In [17]:
y_df_group = y_df.copy()

for i in tqdm(range(len(y_df_group))):
    attack = y_df_group[i]
    group = attack
    if attack in ("DoS Hulk", "DoS GoldenEye", "DoS slowloris", "DoS Slowhttptest"):
        group = "DoS"
    elif attack.startswith("Web Attack"):
        group = "Web Attack"
    elif attack == "FTP-Patator":
        group = "Brute Force FTP"
    elif attack == "SSH-Patator":
        group = "Brute Force SSH"
    
    y_df_group[i] = group

In [23]:
y_df.value_counts()

BENIGN                        2273097
DoS Hulk                       231073
PortScan                       158930
DDoS                           128027
DoS GoldenEye                   10293
FTP-Patator                      7938
SSH-Patator                      5897
DoS slowloris                    5796
DoS Slowhttptest                 5499
Bot                              1966
Web Attack � Brute Force         1507
Web Attack � XSS                  652
Infiltration                       36
Web Attack � Sql Injection         21
Heartbleed                         11
Name: Label, dtype: int64

In [19]:
y_df_group.value_counts()

BENIGN             2273097
DoS                 252661
PortScan            158930
DDoS                128027
Brute Force FTP       7938
Brute Force SSH       5897
Web Attack            2180
Bot                   1966
Infiltration            36
Heartbleed              11
Name: Label, dtype: int64

In [22]:
y_df_enc = pd.get_dummies(y_df_group)

In [23]:
y_df_enc

,BENIGN,Bot,Brute Force FTP,Brute Force SSH,DDoS,DoS,Heartbleed,Infiltration,PortScan,Web Attack
0,1,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0
5,1,0,0,0,0,0,0,0,0,0
6,1,0,0,0,0,0,0,0,0,0
7,1,0,0,0,0,0,0,0,0,0
8,1,0,0,0,0,0,0,0,0,0
9,1,0,0,0,0,0,0,0,0,0
10,1,0,0,0,0,0,0,0,0,0
11,1,0,0,0,0,0,0,0,0,0
12,1,0,0,0,0,0,0,0,0,0
13,1,0,0,0,0,0,0,0,0,0
14,1,0,0,0,0,0,0,0,0,0
15,1,0,0,0,0,0,0,0,0,0
16,1,0,0,0,0,0,0,0,0,0
17,1,0,0,0,0,0,0,0,0,0
18,1,0,0,0,0,0,0,0,0,0
19,1,0,0,0,0,0,0,0,0,0
20,1,0,0,0,0,0,0,0,0,0
21,1,0,0,0,0,0,0,0,0,0
22,1,0,0,0,0,0,0,0,0,0
23,1,0,0,0,0,0,0,0,0,0
24,1,0,0,0,0,0,0,0,0,0
25,1,0,0,0,0,0,0,0,0,0
26,1,0,0,0,0,0,0,0,0,0
27,1,0,0,0,0,0,0,0,0,0
28,1,0,0,0,0,0,0,0,0,0
29,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
2830713,1,0,0,0,0,0,0,0,0,0
2830714,1,0,0,0,0,0,0,0,0,0
2830715,1,0,0,0,0,0,0,0,0,0
2830716,1,0,0,0,0,0,0,0,0,0
2830717,1,0,0,0,0,0,0,0,0,0
2830718,1,0,0,0,0,0,0,0,0,0
2830719,1,0,0,0,0,0,0,0,0,0
2830720,1,0,0,0,0,0,0,0,0,0
2830721,0,0,0,0,0,1,0,0,0,0
2830722,1,0,0,0,0,0,0,0,0,0
2830723,1,0,0,0,0,0,0,0,0,0
2830724,1,0,0,0,0,0,0,0,0,0
2830725,1,0,0,0,0,0,0,0,0,0
2830726,1,0,0,0,0,0,0,0,0,0
2830727,1,0,0,0,0,0,0,0,0,0
2830728,1,0,0,0,0,0,0,0,0,0
2830729,1,0,0,0,0,0,0,0,0,0
2830730,1,0,0,0,0,0,0,0,0,0
2830731,1,0,0,0,0,0,0,0,0,0
2830732,1,0,0,0,0,0,0,0,0,0
2830733,1,0,0,0,0,0,0,0,0,0
2830734,1,0,0,0,0,0,0,0,0,0
2830735,1,0,0,0,0,0,0,0,0,0
2830736,0,0,0,0,0,1,0,0,0,0
2830737,1,0,0,0,0,0,0,0,0,0
2830738,1,0,0,0,0,0,0,0,0,0
2830739,1,0,0,0,0,0,0,0,0,0
2830740,1,0,0,0,0,0,0,0,0,0
2830741,1,0,0,0,0,0,0,0,0,0
2830742,1,0,0,0,0,0,0,0,0,0

# Split data into train and test

In [25]:
from sklearn.model_selection import train_test_split

In [30]:
x_train, x_val, y_train, y_val = train_test_split(x_df_ptscaled, y_df_enc, test_size = 0.1, random_state = 42)

In [34]:
y_train.sum(axis=0)

BENIGN             2045803
Bot                   1772
Brute Force FTP       7113
Brute Force SSH       5326
DDoS                115176
DoS                 227435
Heartbleed               9
Infiltration            33
PortScan            143020
Web Attack            1981
dtype: int64

In [35]:
y_val.sum(axis=0)

BENIGN             227294
Bot                   194
Brute Force FTP       825
Brute Force SSH       571
DDoS                12851
DoS                 25226
Heartbleed              2
Infiltration            3
PortScan            15910
Web Attack            199
dtype: int64

# Train model

In [40]:
from sklearn.ensemble import RandomForestClassifier

In [42]:
clf = RandomForestClassifier(n_estimators=100, random_state=42, verbose=2).fit(x_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed: 54.4min finished

In [45]:
model_id = "randomforest1"

**Save model**

In [43]:
import pickle

In [46]:
import time

model_filename = model_id  + " [" + time.strftime("%Y%m%d %H%M") + "]"

In [47]:
save_file = open(NOTEBOOK_PATH + "Models/" + model_filename + ".pkl", "wb")
saved_model = pickle.dump(clf, save_file)
save_file.close()

**Test model**

In [48]:
pred = clf.predict(x_val)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:   21.6s finished

In [50]:
pred.sum(axis=0)

array([227303,    170,    825,    568,  12846,  25222,      1,      2,
        15939,    193], dtype=uint32)

In [51]:
y_val.sum(axis=0)

BENIGN             227294
Bot                   194
Brute Force FTP       825
Brute Force SSH       571
DDoS                12851
DoS                 25226
Heartbleed              2
Infiltration            3
PortScan            15910
Web Attack            199
dtype: int64

In [69]:
pred_index = list(pred.argmax(1))
y_index = list(np.argmax(y_val.to_numpy(), axis=1))

atktypes = sorted(y_val.columns)
pred_series = pd.Series(pred_index, name="Pred").replace(dict(enumerate(atktypes)))
y_series = pd.Series(y_index, name="Actual").replace(dict(enumerate(atktypes)))

matrix = pd.crosstab(pred_series, y_series, margins=True)
matrix

Actual,BENIGN,Bot,Brute Force FTP,Brute Force SSH,DDoS,DoS,Heartbleed,Infiltration,PortScan,Web Attack,All
Pred,,,,,,,,,,,
BENIGN,227151,40,0,3,7,36,1,1,65,5,227309
Bot,16,154,0,0,0,0,0,0,0,0,170
Brute Force FTP,0,0,825,0,0,0,0,0,0,0,825
Brute Force SSH,0,0,0,568,0,0,0,0,0,0,568
DDoS,2,0,0,0,12844,0,0,0,0,0,12846
DoS,34,0,0,0,0,25188,0,0,0,0,25222
Heartbleed,0,0,0,0,0,0,1,0,0,0,1
Infiltration,0,0,0,0,0,0,0,2,0,0,2
PortScan,91,0,0,0,0,2,0,0,15845,1,15939
Web Attack,0,0,0,0,0,0,0,0,0,193,193
All,227294,194,825,571,12851,25226,2,3,15910,199,283075

# F1 Score

In [70]:
from sklearn.metrics import f1_score

In [71]:
f1_micro = f1_score(y_index, pred_index, average='micro')
f1_macro = f1_score(y_index, pred_index, average='macro')

print(f1_micro)
print(f1_macro)

0.9989260796608672
0.9287448629753092

# Log results

In [72]:
model_log = open(NOTEBOOK_PATH + "model_log.txt", "a")

model_log.write("\n" + model_filename)
model_log.write("\n\tF1 Micro: " + str(f1_micro))
model_log.write("\n\tF1 Macro: " + str(f1_macro))

model_log.close()